import Footer from "@/components/footer";
import Header from "@/components/header";
import Head from "next/head";

export default function Layouts({ children, metaTitle, metaDescription }) {
  return (
    <>
      <Head>
        <title>Next App - {metaTitle || "My app"}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="min-h-screen">{children}</div>
      <Footer />
    </>
  );
}
